var INDEX_BUFFER_FULLSCREEN = 0;
var INDEX_BUFFER_GRID = 1;

var UNIT_TEXTURE_RANDOM_COMPLEX_NUMBERS = 0;
var UNIT_TEXTURE_INIT_HEIGHT_IN_FREQUENCY = 1;
var UNIT_TEXTURE_HEIGHT_AFTER_T_IN_FREQUENCY = 2;
var UNIT_TEXTURE_HEIGHT_AFTER_T_IN_TIME = 3;
var UNIT_TEXTURE_DISPLACEMENT_AFTER_T_IN_FREQUENCY = 4;
var UNIT_TEXTURE_DISPLACEMENT_AFTER_T_IN_TIME = 5;
var UNIT_TEXTURE_PING = 6;
var UNIT_TEXTURE_PONG = 7;

var TRANSFORM_SIZE = 512;

var PHILLIPS_CONST = 0.00003;
var DISPLACEMENT_CONST = 0.01;
var TIME_STEP = 0.01;

var AREA_SIZE = 45;

var WIND_X = 1;
var WIND_Y = -10;






/////////////////CAMERA////////////////

INIT_AZIMUTH =  Math.PI / 3;
MIN_AZIMUTH  =  Number.NEGATIVE_INFINITY;
MAX_AZIMUTH  =  Number.POSITIVE_INFINITY;

INIT_ELEVATION = (45 / 180) * Math.PI;
MIN_ELEVATION  = (15 / 180) * Math.PI;
MAX_ELEVATION  = (75 / 180) * Math.PI;

INIT_DISTANCE = 2.5;
MIN_DISTANCE  = 0;
MAX_DISTANCE  = 1000; 






